version: '3.7'

services:
  psql:
    image: ${POSTGRES_IMAGE:-postgres:14.5-alpine}
    shm_size: 1g
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
      - ./migrations:/migrations
      - ${MIGRATING_DATA:-./migrating-data}:/tmp/

volumes:
  postgresql_data:
